student_admin/class_app/urls.py
from django.urls import path
from . import views

app_name = "class_app"
urlpatterns = [
    path("",views.index,"",name='index'),
]

student_admin/student/urls.py
from django.urls import path
from . import views

app_name="student"
urlpatterns = [
    path("show/",views.index,name="index"),
    path("showOne/<int:id>", views.showOne, name="show"),
    path("search/", views.search, name="search"),
    ]

student_admin/student_admin/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('class/', include('class_app.urls')),
    path('student/',include('student.urls')),
    path('teacher/',include('teacher.urls')),

]

student_admin/teacher/urls.py
from django.urls import path
from .views import MytemplateView,Student_admin

app_name = "teacher"
urlpatterns = [
    path("",MytemplateView.as_view(),name="teacher"),
    path("student",Student_admin.as_view(),name="addStudent")
]

student_admin/class_app/models.py
from django.db import models

# Create your models here.
class Class_app(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

student_admin/student/models.py
from django.db import models
from class_app.models import Class_app
from django.core.validators import MinLengthValidator,MaxLengthValidator,RegexValidator
from django.core.exceptions import ValidationError
# Create your models here.

# def myValidate(value):   # 自定义验证器
#     if value != 'abc':
#         raise ValidationError("不是abc,params={'value:'value'}")

class Student(models.Model):
    name = models.CharField(max_length=20,verbose_name="姓名",null=False,blank=False,
                            error_messages={
                                'black': 'black',
                                'null': 'null',
                                'm1': '不好意思，不能小于2',
                                'm2': '不好意思，不能大于10',
                                'm3': '不好意思，只能是字母',
                            },
                            help_text="请输入姓名",
                            validators=[
                                MinLengthValidator(limit_value=2,message="不能小于2"),
                                MaxLengthValidator(limit_value=10,message="不能大于10"),
                                # RegexValidator(regex="[a-z]+",message="只能是字母",code="m3")
                            ])
    age = models.CharField(max_length=3,verbose_name="性别")
    sex = models.BooleanField(choices=(
        (1,'男'),
        (0,'女')
    ))
    class_id = models.ForeignKey(Class_app,on_delete=models.CASCADE)
    # teacher_id = models.ManyToManyField(to=Teacher,default=0,null=True)   # 多对多

    def __str__(self):
        return self.name

student_admin/teacher/models.py
from django.db import models
from student.models import Student
# Create your models here.

class Teacher(models.Model):
    class Meta():     # 元类 : 对表进行一些设置
        abstract = False
        # app_label = "teacher"
        db_table = "teacher"
    name = models.CharField(max_length=20,verbose_name="姓名")
    project = models.CharField(max_length=20,verbose_name="课程")
    student_id = models.ManyToManyField(to=Student)

    def __str__(self):
        return self.name

student_admin/teacher/forms.py
from django import forms
from student.models import Student

class AddStudent(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name','age','sex','class_id']

student_admin/class_app/views.py
from django.shortcuts import render
from .models import *

# Create your views here.

def index(request):
    res = Class_app.objects.all()
    return render(request,"index.html",{'res':res})

student_admin/student/views.py
from django.shortcuts import render,get_object_or_404
from .models import Student,Class_app

# Create your views here.
def index(request):
    res = Student.objects.all()
    cls = Class_app.objects.all()
    return render(request,"student.html",{'res':res,'cls':cls})

def showOne(request,id):
    res = get_object_or_404(Class_app,pk=id)
    cls = Class_app.objects.all()
    return render(request, "student.html", {'res': res.student_set.all(),'cls':cls})


def search(request):
    name = request.POST.get('name')
    res = Student.objects.filter(name=name).all()
    return render(request,"search.html",{'res':res})

student_admin/teacher/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,View
from .models import Teacher
from student.models import Student
from django.http import HttpResponse
from .forms import AddStudent
# Create your views here.

class MytemplateView(View):
    template_name = "teacher.html"
    def get(self, request):
        res = Teacher.objects.all()
        return render(request,self.template_name,{'res':res})
class Student_admin(View):
    def get(self,request):
        res = AddStudent({ })
        return render(request,"list_student.html",{'form':res.as_p()})
    def post(self,request):
        res = AddStudent(request.POST)
        if res.is_valid():
            print(res.changed_data)
            Student.objects.create(**res.cleaned_data)
            return HttpResponse("ok")
        else:
            return HttpResponse("no")

student_admin/class_app/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>班级列表页</title>
</head>
<body>
<h2>班级列表页</h2>
<ul>
    {% for item in res %}
    <li>
        <a href="">{{ item.name }}</a>
        {% for stu in item.student_set.all %}
            {{ stu.name }}
        {% endfor %}
    </li>
    {% endfor %}
</ul>

</body>
</html>

student_admin/student/templates/search.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
     <table border="1">
        <tr>
            <th>序号</th>
            <th>姓名</th>
            <th>性别</th>
            <th>年龄</th>
            <th>班级</th>
        </tr>
        {% for item in res %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.name }}</td>
                {% if item.sex %}
                    <td>男</td>
                {% else %}
                    <td>女</td>
                {% endif %}
                <td>{{ item.age }}</td>
                <td>{{ item.class_id.name }}</td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

student_admin/student/templates/student.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>学生详情</title>
</head>
<body>
    <h2>学生详情</h2>
    <form action="{% url 'student:search' %}" method="post">
        {% csrf_token %}
        <input type="search" name="name">
        <input type="submit" value="搜索">
    </form>

    <br>

    {% for item in cls %}
        <a href="{% url 'student:show' item.id %}">{{ item.name }}</a>
    {% endfor %}

    <table border="1">
        <tr>
            <th>序号</th>
            <th>姓名</th>
            <th>性别</th>
            <th>年龄</th>
            <th>班级</th>
            <th>老师</th>
        </tr>
        {% for item in res %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.name }}</td>
                {% if item.sex %}
                    <td>男</td>
                {% else %}
                    <td>女</td>
                {% endif %}
                <td>{{ item.age }}</td>
                <td>{{ item.class_id.name }}</td>
                <td>
                    {% for tea in item.teacher_set.all %}
                        {{ tea.name }}、
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

student_admin/teacher/templates/list_student.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="{% url 'teacher:addStudent' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
</body>
</html>

student_admin/teacher/templates/teacher.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h2>教师页面</h2>
    <table border="1">
        <tr>
            <th>序号</th>
            <th>姓名</th>
            <th>课程</th>
            <th>学生</th>
        </tr>
        {% for item in res %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.name }}</td>
                <td>{{ item.project }}</td>
                <td>
                    {% for stu in item.student_id.all %}
                        {{ stu.name }}、
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>